import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const WHATSAPP_NUMBER='917093315923';
const categories=[['🍕','Pizza'],['🍔','Burgers'],['🍜','Noodles'],['🍛','Indian'],['🥗','Healthy'],['🍰','Desserts'],['🥤','Drinks'],['🍗','Chicken']];
const restaurants=[
 {id:1,name:'Urban Spice',cuisine:'Indian • Biryani • North Indian',rating:4.8,time:'25–30 min',price:'₹₹',tag:'20% OFF',emoji:'🍛',accent:'sunset'},
 {id:2,name:'Crust & Co.',cuisine:'Pizza • Italian • Fast Food',rating:4.7,time:'20–25 min',price:'₹₹',tag:'FREE DELIVERY',emoji:'🍕',accent:'berry'},
 {id:3,name:'Burger District',cuisine:'Burgers • American • Fries',rating:4.6,time:'15–20 min',price:'₹',tag:'BUY 1 GET 1',emoji:'🍔',accent:'gold'},
 {id:4,name:'Green Bowl',cuisine:'Healthy • Salads • Bowls',rating:4.9,time:'20–30 min',price:'₹₹',tag:'HEALTHY PICK',emoji:'🥗',accent:'leaf'},
 {id:5,name:'Wok This Way',cuisine:'Asian • Noodles • Chinese',rating:4.7,time:'25–35 min',price:'₹₹',tag:'15% OFF',emoji:'🍜',accent:'night'},
 {id:6,name:'Sweet Theory',cuisine:'Desserts • Cakes • Ice Cream',rating:4.8,time:'15–20 min',price:'₹',tag:'NEW',emoji:'🍰',accent:'rose'}
];
const foods=[
 {id:101,name:'Butter Chicken Biryani',restaurant:'Urban Spice',price:329,old:399,emoji:'🍛',rating:4.9},
 {id:102,name:'Truffle Mushroom Pizza',restaurant:'Crust & Co.',price:449,old:499,emoji:'🍕',rating:4.8},
 {id:103,name:'Smoky Smash Burger',restaurant:'Burger District',price:249,old:299,emoji:'🍔',rating:4.7},
 {id:104,name:'Teriyaki Noodle Bowl',restaurant:'Wok This Way',price:289,old:349,emoji:'🍜',rating:4.8},
 {id:105,name:'Berry Bliss Cheesecake',restaurant:'Sweet Theory',price:219,old:249,emoji:'🍰',rating:4.9},
 {id:106,name:'Avocado Power Bowl',restaurant:'Green Bowl',price:319,old:359,emoji:'🥗',rating:4.8}
];
function App(){
 const [query,setQuery]=useState(''); const [cat,setCat]=useState('All'); const [cart,setCart]=useState([]); const [likes,setLikes]=useState([]); const [toast,setToast]=useState(''); const [showCart,setShowCart]=useState(false); const [showMenu,setShowMenu]=useState(false);
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const add=(food)=>{setCart(c=>{const x=c.find(i=>i.id===food.id);return x?c.map(i=>i.id===food.id?{...i,q:i.q+1}:i):[...c,{...food,q:1}]});notify(`${food.name} added to cart`)};
 const change=(id,d)=>setCart(c=>c.flatMap(i=>i.id===id?(i.q+d>0?[{...i,q:i.q+d}]:[]):[i]));
 const toggleLike=(id)=>setLikes(l=>l.includes(id)?l.filter(x=>x!==id):[...l,id]);
 const results=useMemo(()=>foods.filter(f=>(cat==='All'||f.restaurant===cat)&&`${f.name} ${f.restaurant}`.toLowerCase().includes(query.toLowerCase())),[query,cat]);
 const total=cart.reduce((s,i)=>s+i.price*i.q,0),qty=cart.reduce((s,i)=>s+i.q,0); const discount=Math.min(80,Math.round(total*.2)); const grandTotal=total-discount;
 const orderOnWhatsApp=()=>{if(!cart.length)return;const lines=cart.map(i=>`${i.q} x ${i.name} - ₹${i.price*i.q}`).join('\n');const message=`🍔 *CRAVIO ORDER*\n\n${lines}\n\n━━━━━━━━━━━━━━\nSubtotal: ₹${total}\nDelivery: FREE\nDiscount: -₹${discount}\n*TOTAL: ₹${grandTotal}*\n\n📍 Delivery address: Please share your location/address here.\n\nThank you for ordering from Cravio!`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank');notify('Order bill opened in WhatsApp')};
 return <div className="app">
  <header className="nav"><a className="brand" href="#home"><span className="brand-mark">C</span><span>cravio</span></a><nav className={showMenu?'open':''}><a href="#home">Home</a><a href="#restaurants">Restaurants</a><a href="#popular">Popular</a><a href="#offers">Offers</a></nav><div className="nav-actions"><button className="icon-btn" onClick={()=>notify('Location selector coming soon')} aria-label="location">⌖</button><button className="cart-btn" onClick={()=>setShowCart(true)}>🛒 <span>Cart</span>{qty>0&&<b>{qty}</b>}</button><button className="avatar" onClick={()=>notify('Profile coming soon')}>R</button><button className="hamb" onClick={()=>setShowMenu(!showMenu)}>☰</button></div></header>
  <main id="home">
   <section className="hero"><div className="hero-copy"><div className="eyebrow"><span>✦</span> YOUR CRAVINGS, DELIVERED</div><h1>Good food.<br/><em>Great mood.</em></h1><p>Discover local favorites, hidden gems, and everything you’re craving — delivered to your door.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for dishes, restaurants..."/><button onClick={()=>document.getElementById('popular').scrollIntoView({behavior:'smooth'})}>Search</button></div><div className="hero-meta"><span>⚡ 25 min avg. delivery</span><span>★ 4.8 average rating</span><span>◎ 100% secure</span></div></div><div className="hero-art"><div className="orbit o1"></div><div className="orbit o2"></div><div className="plate">🍕</div><div className="float-card card-a"><span>🔥</span><div><b>Trending</b><small>Truffle Pizza</small></div></div><div className="float-card card-b"><span>★</span><div><b>4.9</b><small>2.4k reviews</small></div></div><div className="scribble">made with<br/>cravings ↗</div></div></section>
   <section className="categories"><div className="section-head"><div><span className="mini-label">EXPLORE</span><h2>What are you craving?</h2></div><button className="arrow" onClick={()=>document.getElementById('popular').scrollIntoView({behavior:'smooth'})}>See all →</button></div><div className="cat-row"><button className={cat==='All'?'cat active':'cat'} onClick={()=>setCat('All')}><span>✨</span>All</button>{categories.map(([e,n])=><button key={n} className="cat" onClick={()=>{setCat(n==='Indian'?'Urban Spice':n==='Pizza'?'Crust & Co.':n==='Burgers'?'Burger District':n==='Noodles'?'Wok This Way':n==='Healthy'?'Green Bowl':n==='Desserts'?'Sweet Theory':'All');document.getElementById('popular').scrollIntoView({behavior:'smooth'})}}><span>{e}</span>{n}</button>)}</div></section>
   <section className="section" id="restaurants"><div className="section-head"><div><span className="mini-label">HANDPICKED FOR YOU</span><h2>Top restaurants</h2></div><button className="arrow">View all →</button></div><div className="restaurant-grid">{restaurants.map(r=><article className="restaurant" key={r.id}><div className={`rest-img ${r.accent}`}><span className="tag">{r.tag}</span><button className="heart" onClick={()=>toggleLike(r.id)}>{likes.includes(r.id)?'♥':'♡'}</button><div className="food-emoji">{r.emoji}</div><span className="time">⚡ {r.time}</span></div><div className="rest-info"><div><h3>{r.name}</h3><p>{r.cuisine}</p></div><span className="rating">★ {r.rating}</span></div><div className="rest-bottom"><span>{r.price} • Fast delivery</span><button onClick={()=>notify(`Opening ${r.name}`)}>View menu →</button></div></article>)}</div></section>
   <section className="offer" id="offers"><div><span className="mini-label">CRAVIO EXCLUSIVE</span><h2>Hungry for a<br/><em>little extra?</em></h2><p>Get 20% off your first 3 orders. Use code <strong>CRAVE20</strong> at checkout.</p><button onClick={()=>notify('CRAVE20 copied!')}>Grab the offer <span>↗</span></button></div><div className="offer-art"><div className="burst">20%</div><div className="offer-food">🍔</div><span>OFF</span></div></section>
   <section className="section" id="popular"><div className="section-head"><div><span className="mini-label">MOST LOVED</span><h2>{query?'Search results':'Popular right now'}</h2></div><div className="filters"><button className={cat==='All'?'selected':''} onClick={()=>setCat('All')}>All</button><button onClick={()=>notify('Rating filter coming soon')}>★ 4.5+</button><button onClick={()=>notify('Fast delivery filter coming soon')}>⚡ Fast</button></div></div><div className="food-grid">{results.map(f=><article className="food-card" key={f.id}><div className="food-img"><span>{f.emoji}</span><button className="heart" onClick={()=>toggleLike(f.id)}>{likes.includes(f.id)?'♥':'♡'}</button><div className="food-rating">★ {f.rating}</div></div><div className="food-info"><p>{f.restaurant}</p><h3>{f.name}</h3><div><strong>₹{f.price}</strong><del>₹{f.old}</del><button onClick={()=>add(f)}>+ Add</button></div></div></article>)}{results.length===0&&<div className="empty">No cravings found. Try “pizza”, “burger”, or “biryani”.</div>}</div></section>
  </main>
  <footer><div className="brand footer-brand"><span className="brand-mark">C</span><span>cravio</span></div><p>Made for cravings. Built for moments.</p><div><a>Instagram</a><a>Twitter</a><a>LinkedIn</a></div></footer>
  {showCart&&<div className="overlay" onClick={()=>setShowCart(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="mini-label">YOUR ORDER</span><h2>Cart <small>({qty})</small></h2></div><button onClick={()=>setShowCart(false)}>×</button></div>{cart.length===0?<div className="empty cart-empty"><span>🛒</span><h3>Your cart is empty</h3><p>Add something delicious and it’ll appear here.</p><button onClick={()=>setShowCart(false)}>Explore food</button></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><span className="cart-emoji">{i.emoji}</span><div><b>{i.name}</b><small>₹{i.price}</small></div><div className="stepper"><button onClick={()=>change(i.id,-1)}>−</button><span>{i.q}</span><button onClick={()=>change(i.id,1)}>+</button></div></div>)}</div><div className="bill"><div><span>Subtotal</span><b>₹{total}</b></div><div><span>Delivery</span><b className="free">FREE</b></div><div><span>Discount</span><b>− ₹{discount}</b></div><hr/><div className="grand"><span>Total</span><b>₹{grandTotal}</b></div><button className="checkout" onClick={orderOnWhatsApp}>Order on WhatsApp <span>↗</span></button><small className="whatsapp-note">Your itemized bill will open in WhatsApp to place the order.</small></div></>}</aside></div>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
